-- ============================================
-- MySQL Schema for Chunked Upload System
-- ============================================

-- Create database
CREATE DATABASE IF NOT EXISTS chunk_uploads
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE chunk_uploads;

-- ============================================
-- Uploads Table
-- ============================================
-- Stores metadata about each upload session
CREATE TABLE IF NOT EXISTS uploads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    -- Unique identifier generated by frontend (filename + size hash)
    upload_id VARCHAR(100) NOT NULL UNIQUE,
    
    -- Original filename
    filename VARCHAR(500) NOT NULL,
    
    -- Total file size in bytes
    total_size BIGINT UNSIGNED NOT NULL,
    
    -- Total number of chunks
    total_chunks INT UNSIGNED NOT NULL,
    
    -- Upload status
    -- UPLOADING: chunks are being received
    -- PROCESSING: all chunks received, finalizing
    -- COMPLETED: upload finished successfully
    -- FAILED: upload failed permanently
    status ENUM('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'UPLOADING',
    
    -- SHA-256 hash of the completed file (set after finalization)
    final_hash VARCHAR(64) NULL,
    
    -- JSON array of top-level ZIP contents (set after finalization)
    zip_contents JSON NULL,
    
    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for common queries
    INDEX idx_upload_id (upload_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_updated_at (updated_at)
) ENGINE=InnoDB;

-- ============================================
-- Chunks Table
-- ============================================
-- Tracks the status of each chunk for an upload
CREATE TABLE IF NOT EXISTS chunks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    -- Foreign key to uploads table
    upload_id INT NOT NULL,
    
    -- Zero-based chunk index
    chunk_index INT UNSIGNED NOT NULL,
    
    -- Chunk status
    -- PENDING: chunk not yet received
    -- RECEIVED: chunk successfully received and written
    status ENUM('PENDING', 'RECEIVED') NOT NULL DEFAULT 'PENDING',
    
    -- When the chunk was received
    received_at TIMESTAMP NULL,
    
    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraint
    CONSTRAINT fk_chunks_upload_id 
        FOREIGN KEY (upload_id) REFERENCES uploads(id) 
        ON DELETE CASCADE,
    
    -- Unique constraint: one record per chunk per upload
    UNIQUE KEY uk_upload_chunk (upload_id, chunk_index),
    
    -- Indexes
    INDEX idx_upload_id (upload_id),
    INDEX idx_status (status),
    INDEX idx_chunk_index (chunk_index)
) ENGINE=InnoDB;

-- ============================================
-- Useful Queries
-- ============================================

-- Get upload progress
-- SELECT 
--     u.upload_id,
--     u.filename,
--     u.total_chunks,
--     COUNT(CASE WHEN c.status = 'RECEIVED' THEN 1 END) as received_chunks,
--     ROUND(COUNT(CASE WHEN c.status = 'RECEIVED' THEN 1 END) / u.total_chunks * 100, 2) as progress_percent
-- FROM uploads u
-- LEFT JOIN chunks c ON u.id = c.upload_id
-- WHERE u.upload_id = ?
-- GROUP BY u.id;

-- Find orphaned uploads (older than 24 hours)
-- SELECT upload_id, filename, status, created_at
-- FROM uploads
-- WHERE status IN ('UPLOADING', 'FAILED')
-- AND updated_at < DATE_SUB(NOW(), INTERVAL 24 HOUR);

-- Get chunk status summary for an upload
-- SELECT 
--     status,
--     COUNT(*) as count
-- FROM chunks
-- WHERE upload_id = ?
-- GROUP BY status;
